### ISSUE TITLE
Lucene index shouldn't be used with = operator

### ISSUE THREAD

**Issue by kgreenpea** [orientechnologies/orientdb-lucene#44]
I would have expected = operator to perform an exact match, instead the lucene index is being used.

I found following discussion, but can't see a related issue or apparent fix? https://groups.google.com/forum/#!topic/orient-database/ENp6U6JUo8w

e.g.
SELECT value from Action where value = 'do something else'

Yields:
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "value": "do something"
        }
    ],
    "notification": "Query executed in 0.014 sec. Returned 1 record(s)"
}

**Comment by Tielman** [comment]
I wouldn't call this a *bug*, it's more that there is currently no obvious way to do an exact string match on a column with a Lucene index. This "fix" implied that we would be able to do so by using "=" instead of "LUCENE", but it doesn't seem to work that way, at least if this has been incorporated into 2.1-rc2.
